# Generated by Django 2.1.1 on 2018-10-09 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QoldanushiProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sipattama', models.CharField(default='', max_length=500)),
                ('k_b_zhumis_zh', models.CharField(default='Kim bolip zhumis isteisiz? Misali: Python Developer', max_length=100)),
                ('qala', models.CharField(default='', max_length=100)),
                ('website', models.URLField(default='')),
                ('ualy_tel', models.IntegerField(default=0)),
                ('qoldanushi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
